//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NUnit.Framework;
using System;


namespace Dnum.Test
{
	[TestFixture]
	public class DnumTest
	{
		[Flags] public enum PetType
		{
		   None = 0, Dog = 1, Cat = 2, Rodent = 4, Bird = 8, Reptile = 16, Other = 32
		};
		
		[Test]
		public void TestIsDefined()
		{
			

		}
		
	}
}
